[package]
name = "j4fsmb-server"
version = "0.0.1"
authors = ["squeakbug <squeakbug73@outlook.com>"]
edition = "2021"

[dependencies]
tokio.workspace = true
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
